services:
  university_domains_list_api:
    container_name: university_domains_list_api_app
    image: university_domains_list
    build:
      context: .
      dockerfile: python.Dockerfile
    command: bash -c "python app.py"
    ports:
      - "8000:8000"
    volumes:
      - ".:/university-domains-list-api"
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx:1.25.0
    container_name: university_domains_list_api_nginx
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./.data/logs/nginx:/var/log/nginx"
    restart: unless-stopped
